// 线路 <-> 地区省份 名称映射表
export const lineToProvinceMap: { [key: string]: string } = {
  beijing: '北京市',
  tianjin: '天津市',
  hebei: '河北省',
  shanxi: '山西省',
  neimenggu: '内蒙古自治区',
  liaoning: '辽宁省',
  jilin: '吉林省',
  heilongjiang: '黑龙江省',
  shanghai: '上海市',
  jiangsu: '江苏省',
  zhejiang: '浙江省',
  anhui: '安徽省',
  fujian: '福建省',
  jiangxi: '江西省',
  shandong: '山东省',
  henan: '河南省',
  hubei: '湖北省',
  hunan: '湖南省',
  guangdong: '广东省',
  guangxi: '广西壮族自治区',
  hainan: '海南省',
  chongqing: '重庆市',
  sichuan: '四川省',
  guizhou: '贵州省',
  yunnan: '云南省',
  xizang: '西藏自治区',
  shaanxi: '陕西省',
  gansu: '甘肃省',
  qinghai: '青海省',
  ningxia: '宁夏回族自治区',
  xinjiang: '新疆维吾尔自治区',
  taiwan: '台湾省',
  xianggang: '香港特别行政区',
  aomen: '澳门特别行政区',
};

// 地区省份 <-> 线路 名称映射表
export const provinceToLineMap: { [key: string]: string } = {
  北京市: 'beijing',
  天津市: 'tianjin',
  河北省: 'hebei',
  山西省: 'shanxi',
  内蒙古自治区: 'neimenggu',
  辽宁省: 'liaoning',
  吉林省: 'jilin',
  黑龙江省: 'heilongjiang',
  上海市: 'shanghai',
  江苏省: 'jiangsu',
  浙江省: 'zhejiang',
  安徽省: 'anhui',
  福建省: 'fujian',
  江西省: 'jiangxi',
  山东省: 'shandong',
  河南省: 'henan',
  湖北省: 'hubei',
  湖南省: 'hunan',
  广东省: 'guangdong',
  广西壮族自治区: 'guangxi',
  海南省: 'hainan',
  重庆市: 'chongqing',
  四川省: 'sichuan',
  贵州省: 'guizhou',
  云南省: 'yunnan',
  西藏自治区: 'xizang',
  陕西省: 'shaanxi',
  甘肃省: 'gansu',
  青海省: 'qinghai',
  宁夏回族自治区: 'ningxia',
  新疆维吾尔自治区: 'xinjiang',
  台湾省: 'taiwan',
  香港特别行政区: 'xianggang',
  澳门特别行政区: 'aomen',
};
